// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/AbdulRasyid-Ans/xyz-multifinance/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// ConsumerLimitUsecase is an autogenerated mock type for the ConsumerLimitUsecase type
type ConsumerLimitUsecase struct {
	mock.Mock
}

// CreateOrUpdateConsumerLimit provides a mock function with given fields: ctx, request
func (_m *ConsumerLimitUsecase) CreateOrUpdateConsumerLimit(ctx context.Context, request usecase.ConsumerLimitRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateConsumerLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ConsumerLimitRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteConsumerLimit provides a mock function with given fields: ctx, consumerLimitID
func (_m *ConsumerLimitUsecase) DeleteConsumerLimit(ctx context.Context, consumerLimitID int64) error {
	ret := _m.Called(ctx, consumerLimitID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConsumerLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, consumerLimitID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConsumerLimitByConsumerID provides a mock function with given fields: ctx, consumerID
func (_m *ConsumerLimitUsecase) GetConsumerLimitByConsumerID(ctx context.Context, consumerID int64) ([]usecase.GetConsumerLimitResponse, error) {
	ret := _m.Called(ctx, consumerID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsumerLimitByConsumerID")
	}

	var r0 []usecase.GetConsumerLimitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]usecase.GetConsumerLimitResponse, error)); ok {
		return rf(ctx, consumerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []usecase.GetConsumerLimitResponse); ok {
		r0 = rf(ctx, consumerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecase.GetConsumerLimitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, consumerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLimitByTenureAndConsumerID provides a mock function with given fields: ctx, tenure, consumerID
func (_m *ConsumerLimitUsecase) GetLimitByTenureAndConsumerID(ctx context.Context, tenure int16, consumerID int64) (usecase.GetConsumerLimitResponse, error) {
	ret := _m.Called(ctx, tenure, consumerID)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitByTenureAndConsumerID")
	}

	var r0 usecase.GetConsumerLimitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int16, int64) (usecase.GetConsumerLimitResponse, error)); ok {
		return rf(ctx, tenure, consumerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int16, int64) usecase.GetConsumerLimitResponse); ok {
		r0 = rf(ctx, tenure, consumerID)
	} else {
		r0 = ret.Get(0).(usecase.GetConsumerLimitResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int16, int64) error); ok {
		r1 = rf(ctx, tenure, consumerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConsumerLimitUsecase creates a new instance of ConsumerLimitUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerLimitUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerLimitUsecase {
	mock := &ConsumerLimitUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
