// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/AbdulRasyid-Ans/xyz-multifinance/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MerchantRepository is an autogenerated mock type for the MerchantRepository type
type MerchantRepository struct {
	mock.Mock
}

// CreateMerchant provides a mock function with given fields: ctx, merchant
func (_m *MerchantRepository) CreateMerchant(ctx context.Context, merchant repository.Merchant) (int64, error) {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchant")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Merchant) (int64, error)); ok {
		return rf(ctx, merchant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Merchant) int64); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Merchant) error); ok {
		r1 = rf(ctx, merchant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMerchant provides a mock function with given fields: ctx, id
func (_m *MerchantRepository) DeleteMerchant(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchMerchant provides a mock function with given fields: ctx, req
func (_m *MerchantRepository) FetchMerchant(ctx context.Context, req repository.FetchMerchantRequest) ([]repository.Merchant, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FetchMerchant")
	}

	var r0 []repository.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.FetchMerchantRequest) ([]repository.Merchant, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.FetchMerchantRequest) []repository.Merchant); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.FetchMerchantRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantByID provides a mock function with given fields: ctx, id
func (_m *MerchantRepository) GetMerchantByID(ctx context.Context, id int64) (repository.Merchant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantByID")
	}

	var r0 repository.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (repository.Merchant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) repository.Merchant); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Merchant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMerchant provides a mock function with given fields: ctx, merchant
func (_m *MerchantRepository) UpdateMerchant(ctx context.Context, merchant repository.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMerchantRepository creates a new instance of MerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantRepository {
	mock := &MerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
